apiVersion: 1

datasources:
  - name: "InfluxDB v2 (Cavaon)"
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: cavaon
      defaultBucket: exercise
      tlsSkipVerify: true
    secureJsonData:
      token: $INFLUXDB_TOKEN
    version: 1
    editable: false
